version: "3"
services:
  database:
    image: postgres:9.6
    volumes:
      - ./tools/postgres-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: contentfirst
networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/16
