version: '3'
services:
  database:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: postgres:9.6
    volumes:
      - ./tools/postgres-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: contentfirst, storage
  minismaug:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-ux.dbc.dk/serviceprovider:latest
    entrypoint:
      - npm
      - run
      - start:minismaug
  storage:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-ux.dbc.dk/serviceprovider:latest
    env_file: ./docker/serviceprovider.docker
    depends_on:
      - database
      - minismaug
      - web
    command: bash -c 'until $$(curl --output /dev/null --silent --head --fail http://web:3000/ready); do printf '.'; sleep 5; done; node src/main.js'
  web:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: '${IMAGE:-docker-ux.dbc.dk/content-first:latest}'
    env_file: ./docker/env.docker
    depends_on:
      - database
    command: bash -c 'node src/server/main.js'
  injectmeta:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: '${IMAGE:-docker-ux.dbc.dk/content-first:latest}'
    env_file: ./docker/env.docker
    environment:
      - HOST=http://web
    depends_on:
      - web
    command: bash -c 'touch current.env; npm run fetch-inject-metakompas'
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker.dbc.dk/cypress:latest
    volumes:
      - './e2e:/app/e2e'
    depends_on:
      - injectmeta
      - storage
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: bash -c 'until $$(curl --output /dev/null --silent --head --fail http://web:3000/v1/test/initStorage); do printf '.'; sleep 5; done; npm run cy'
