version: "3"
services:
  database:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: postgres:9.6
    volumes:
      - ./tools/postgres-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: contentfirst,storage
  storage:
    image: docker-ux.dbc.dk/serviceprovider-master:latest
    env_file: ./docker/serviceprovider.docker
    depends_on:
      - database
      - minismaug
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; node src/main.js'
  minismaug:
    image: docker-ux.dbc.dk/serviceprovider-master:latest
    entrypoint:
      - npm
      - run
      - start:minismaug
  contentfirst:
    env_file: ./docker/dev.docker
    depends_on:
      - database
      - storage
    image: docker.dbc.dk/node10:latest
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: bash -c 'npm install && npm run postinstall && npm run start'
    ports:
      - 3000:3000
      - 3001:3001
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1400