version: '3'
services:
  database:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: postgres:9.6
    volumes:
      - ./tools/postgres-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: contentfirst, storage
  minismaug:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-ux.dbc.dk/serviceprovider:6
    entrypoint:
      - npm
      - run
      - start:minismaug
  storage:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-ux.dbc.dk/serviceprovider:6
    env_file: ./docker/serviceprovider.docker
    depends_on:
      - database
      - minismaug
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; sleep 5; node src/main.js'
  web:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: '${IMAGE:-docker-ux.dbc.dk/content-first:latest}'
    env_file: ./docker/env.docker
    depends_on:
      - database
      - storage
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; sleep 5; node src/server/main.js'
  injectmeta:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: '${IMAGE:-docker-ux.dbc.dk/content-first:latest}'
    env_file: ./docker/env.docker
    environment:
      - HOST=http://web
    depends_on:
      - web
    command: bash -c 'touch current.env; npm run fetch-inject-metakompas'
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker.dbc.dk/cypress:10
    volumes:
      - './e2e:/app/e2e'
    depends_on:
      - injectmeta
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: bash -c 'sleep 30; npm run cy'
    networks:
  default:
    ipam:
      config:
        - subnet: 192.168.0.0/16

