version: "3"
services:
  database:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: postgres:9.6
    volumes:
      - ./tools/postgres-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: contentfirst
  web:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: '${IMAGE:-docker-ux.dbc.dk/content-first:latest}'
    env_file: ./docker/env.docker
    depends_on:
      - database
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; node src/server/main.js'
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker.dbc.dk/cypress:latest
    volumes:
      - './e2e:/app/e2e'
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: npm run cy

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/16
